server:
  port: 9081

spring:
  rabbitmq:
    port: 5672
    host: 13.209.204.63
    username: guest
    password: guest

  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/Chat
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:

  datasource: # mysql 설정
    url: jdbc:mysql://catchme-member-db-mysql.c2yclqqipmlk.ap-northeast-2.rds.amazonaws.com:3306/chat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: catchme!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql


logging:
  level:
    org:
      hibernate:
        SQL: debug